[package]
name = "arena"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
env_logger = "0.11.2"
splendor_tourney = { path = "../lib" }
tokio = "1.36.0"

